name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Android SDK Path
      run: |
        echo "ANDROID_HOME is set to $ANDROID_HOME"
        ls -al $ANDROID_HOME

    - name: Set up Java and Android SDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set Android SDK environment variables
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        PATH: $PATH:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/platform-tools
      run: |
        echo "ANDROID_HOME is set to $ANDROID_HOME"
        echo "PATH is set to $PATH"

    - name: Accept Android SDK licenses
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        PATH: $PATH:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/platform-tools
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Install dependencies
      run: |
        pip install buildozer
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade Cython==0.29.33
        export PATH=$PATH:~/.local/bin/
    


    - name: Build Android App
      run: |
        pwd
        buildozer android debug -y
        mv bin/YourAppName-debug.apk bin/YourAppName-v1.0-debug.apk

    - name: Upload APK for testing
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/YourAppName-v1.0-debug.apk
