name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install buildozer
        # 以下是从Buildozer 0.11文档拿来的
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade Cython==0.29.33  # the --user should be removed if you do this in a venv

        # add the following line at the end of your ~/.bashrc file
        export PATH=$PATH:~/.local/bin/
        

    - name: Build Android App
      run: |
        pwd
        # buildozer init 如果没有buildozer.spec则需要这行,然后添加参数
        sdkmanager --update --licenses
        buildozer android debug
        # 假设生成的 APK 在 bin/目录下，这里将其重命名以便区分不同的构建版本
        mv bin/YourAppName-debug.apk bin/YourAppName-v1.0-debug.apk

    - name: Upload APK for testing
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/YourAppName-v1.0-debug.apk
