name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Locate sdkmanager and accept licenses
      run: |
        SDKMANAGER_PATH=$(find $ANDROID_HOME -type f -name "sdkmanager" | head -n 1)
        if [ -z "$SDKMANAGER_PATH" ]; then
          echo "sdkmanager not found!"
          exit 1
        else
          echo "sdkmanager located at $SDKMANAGER_PATH"
          echo "y" | $SDKMANAGER_PATH --licenses
        fi
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Install dependencies
      run: |
        pip install buildozer
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade Cython==0.29.33
        export PATH=$PATH:~/.local/bin/
    


    - name: Build Android App
      run: |
        pwd
        buildozer android debug -y
        mv bin/YourAppName-debug.apk bin/YourAppName-v1.0-debug.apk

    - name: Upload APK for testing
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/YourAppName-v1.0-debug.apk
